### PR TITLE
Bring tide to root, and allow `cargo run --example`

### PR DESCRIPTION
**Pull request by yoshuawuyts**
## Description
Moves the tide submodule to the root of the crate, allows running examples using:
```sh
$ cargo run --example <example>
```
Also makes the examples to be run standalone without a need for `lib.rs`. Ref https://github.com/rustasync/tide/issues/223.

## Motivation and Context
This patch is an alternative to #227. As explained in https://github.com/rustasync/tide/issues/223#issuecomment-494184444, I think it's preferable if we keep Cargo's default behavior of being able to run examples using `cargo run --example`.

I spent some time today trying to figure out how to run our examples, only to find out that they weren't runnable, which was unexpected, and admittedly rather frustrating.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/rustasync/tide/blob/master/.github/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by prasannavl** [comment]
Awesome! I do think this is much nicer, and also keeps things consistent with `runtime`. My initial motivation to not go this route, was that we may have to tweak tooling scaffolds and other experience if porting over from `futures`, `tokio`, etc. 

But yeah, we can take the new path and figure things out as we go :)

**Comment by fairingrey** [comment]
This approach is neat, reminds me of the way actix-web is laid out (with the main crate at root, so we no longer rely on a workspace manifest alone). I like it :+1: 

PS: Thanks for fixing my example!

**Comment by prasannavl** [comment]
If the travis bit can be fixed, I think we can merge this and handle the example clippy warnings post merge, for this particular instance.

**Comment by fairingrey** [comment]
@prasannavl Yup, after these Travis runs finish, clippy should only be yelling at the examples (and we can just get those fixed up in a later PR)

**Comment by fairingrey** [comment]
Clippy freaks out on the examples, but as mentioned before we can fix it later -- merging!

**Pull request merged**
