### PR TITLE
[WIP] Update futures-preview to 0.3.0-alpha.16

### PR DESCRIPTION
**Pull request by taiki-e**
## Description

`await` syntax was implemented in https://github.com/rust-lang/rust/pull/60586, and nightly-2019-05-09 has been released with the changes. Also, `await!` macro will be removed in the future.

Then, futures 0.3.0-alpha.16 was released.

Refs: [migration tool](https://github.com/taiki-e/replace-await)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

With this change, the minimum required version will go up to nightly-2019-05-09.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/rustasync/tide/blob/master/.github/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by secretfader** [comment]
Ideally, we'd probably want to pair this PR with one containing similar changes to [Tide](https://github.com/rustasync/tide). Is this something you'd want to handle, @taiki-e? (Another team member can if you'd prefer not to.)

**Comment by secretfader** [comment]
:+1: Looks good to me. I see the PR with changes to Tide, as well.

**Comment by taiki-e** [comment]
futures 0.3.0-alpha.16 was released, so I added a commit and updated this PR.

**Comment by taiki-e** [comment]
Then, this PR blocked on https://github.com/rustasync/http-service/pull/28.

**Pull request merged**
