### PR TITLE
Remove usage of async_closure

### PR DESCRIPTION
**Pull request by taiki-e**
## Motivation and Context

`async_closure` won't be stable any time soon and are equivalent to closures which return async blocks. 

Related: https://github.com/rust-lang-nursery/futures-rs/pull/1716#issuecomment-508964777

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/rustasync/tide/blob/master/.github/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by secretfader** [comment]
I recently added `async_closure` support to [`http-service`](https://github.com/rustasync/http-service) during an effort to fixbuilds on recent nightlies, and I'm happy to remove it if this is merged. Anything that moves us towards stability sooner rather than later gets my vote. :+1:

**Comment by secretfader** [comment]
I recently added the `async_closure` feature flag to [`http-service`](https://github.com/rustasync/http-service) during an effort to fix builds on recent nightlies, and I'm happy to remove it if this is merged. Anything that moves us towards stability sooner rather than later gets my vote. :+1:

**Comment by fairingrey** [comment]
This looks pretty simple enough, thanks for the help! :+1:

I'll be looking at updating other libraries in rust-async to follow this change soon, probably.

**Comment by secretfader** [comment]
Since this feature gate is [currently deferred](https://github.com/rust-lang/rust/issues/62290), I favor moving other libraries to match the standard set by this PR.

**Pull request merged**
