### PR TITLE
Rename EndpointResult to Result

### PR DESCRIPTION
**Pull request by k-nasa**
## Description

Rename EndptResult to Result.

## Motivation and Context

https://github.com/rustasync/tide/issues/235

## How Has This Been Tested?

Compile all and run test code

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/rustasync/tide/blob/master/.github/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by k-nasa** [comment]
@prasannavl In the example, I think it is more intuitive to return a simple Result. However, for tide developers, it may not be desirable to change "EndpointResult" to "Result".

I have this idea. By defining tide :: Result as an alias of EndpointResult, user use  'Result', tide developer use EndpointResult.  What do you think?

**Comment by k-nasa** [comment]
@prasannavl  ?

**Comment by prasannavl** [comment]
Hi @k-nasa - Sorry, been a bit busy. I'm keen to see that others think of this. Meanwhile https://github.com/rustasync/tide/issues/235#issuecomment-495981039.

**Comment by k-nasa** [comment]
@prasannavl Ok. thanks!  And sorry to rush

**Pull request closed without merging**
