### PR TITLE
fix: sync up with nightly futures_api

### PR DESCRIPTION
**Pull request by prasannavl**
Sync up the new changes in the nightly futures_api: futures dependency to 0.3.0-alpha.14
Also, updated all patch versions of other deps, while at it.

Blocker for successful build/release: https://github.com/rustasync/http-service/pull/14

### CODE REVIEW

**Comment by prasannavl** [comment]
https://github.com/rustasync/http-service/pull/14 has landed, but probably needs https://github.com/rustasync/http-service/pull/17 too to land now. 

Meanwhile, updated the http-service-* versions to correspond to the bumped versions.

**Comment by aturon** [comment]
@prasannavl do you want to disable clippy on the travis config? We keep getting nightlies without it, which renders CI useless.

**Comment by prasannavl** [comment]
@aturon - ah, I did check for the nightly where everything built. Looks like I was off by 1 day. Fixed it up to later nightly. Hopefully, this should build (unless I was off by one day again).

**Comment by prasannavl** [comment]
Wait. What? This looks like bogus lint failures. (Although there are other linting pragmas that could be added and probably needs fixing like Debug impls for a bunch. But will open a separate PR for that.)

I think this is ready to be merged.

**Comment by aturon** [comment]
Weird error from Travis -- wanna take a look? Otherwise I can grab this locally and see if I can figure it out...

**Comment by prasannavl** [comment]
I assumed it probably had to do with async await that clippy likely hadn't caught up yet. My first thought was to add `#[allow(clippy::needless_lifetimes)]`, which should fix this -- unless there's something I'm missing. 

Thought I'll do another PR with that and some more clippy pragmas next - but yes, would be helpful if you could just make sure that was a bogus lint error and I'm not missing something.

**Comment by Nemo157** [comment]
@prasannavl I opened https://github.com/rust-lang/rust-clippy/issues/3988 for it, it's definitely a clippy bug that it's warning about the lifetime generated as part of the async desugaring.

**Comment by yoshuawuyts** [comment]
@prasannavl I'm +1 on adding `#[allow(clippy::needless_lifetimes)]` to squash the errors. If we then open a tracking issue that links to the clippy bug we can fix this once the clippy issue is resolved.

**Comment by prasannavl** [comment]
@yoshuawuyts - Done. So sorry, instead of a PR, I accidentally committed it directly on the master (forgetting I had commit rights on now)

**Comment by yoshuawuyts** [comment]
Related lifetimes issues:
- https://github.com/rust-lang-nursery/futures-rs/pull/1534
- https://github.com/rust-lang/rust/issues/52675

**Comment by yoshuawuyts** [comment]
@prasannavl hah, yeah no worries. -- could you rebase on master then tho so we can get this build to pass?

**Comment by prasannavl** [comment]
yup, just doing that locally, and tests were still failing due to examples failing - so seeing if I can fix it quickly, otherwise will just push it rebased

**Comment by prasannavl** [comment]
Looks like the recent PR #177 https://github.com/rustasync/tide/commit/9e0a19ad2ed6168737a44d9f82c00453f9ef8260, was causing the failed doc tests after the futures api update.  

All fixed, and we're building again!

**Pull request merged**
