### PR TITLE
add elapsed field to logger

### PR DESCRIPTION
**Pull request by leaxoy**

### CODE REVIEW

**Comment by KodrAus** [comment]
Hi @leaxoy! :wave:

It's definitely useful to be able to collect timings about how long a piece of middleware takes to execute, but in my opinion this is best solved through some kind of contextual logging where we can choose what blocks of code to wrap for timings.

**Comment by leaxoy** [comment]
Wrap the user logic maybe useful. Then we can add some code around `RequestContext.next` call with insert time field to `Request.extensions`, which can be used whenever it's needed.

**Comment by prasannavl** [comment]
Hi @leaxoy! Does #222 resolve this? :)

**Comment by leaxoy** [comment]
Looks cover this.

**Pull request closed without merging**
