### PR TITLE
Add doc example showing query parameter extraction

### PR DESCRIPTION
**Pull request by phansch**
## Description

This adds a doc test that shows how to parse the URL query into a `HashMap`.

## Motivation and Context

I found this not very well documented and hope the docs will save some time.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/rustasync/tide/blob/master/.github/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phansch** [comment]
Thinking a bit more about this, I believe my main problem was initially that `ContextExt`/`querystring` were not easily discoverable in the docs; This PR doesn't really address that.

Would you be fine with also adding this example to the docs in `App`?

**Comment by secretfader** [comment]
Thanks for including an example. I wrote this crate as Tide was just beginning to stabilize, with the goal of coming back and adding doctests later. 

As you noticed, that never happened! 

I agree that it's reasonable to include a link to this example in docs for App, but I'm unsure about how to best proceed, since I'm not an expert on rustdoc. 

As is, this PR already adds significant value. Maybe we open an issue on the topic of docs and interlinking? I'm willing to bet we have a bunch of cases similar to this one, across the Tide ecosystem.

**Comment by phansch** [comment]
> Maybe we open an issue on the topic of docs and interlinking? 

Sounds like the best approach to me :+1:

**Comment by secretfader** [comment]
Cool. I'll go ahead and merge this PR. Thanks for your help! :+1:

**Pull request merged**
