### PR TITLE
Reorganize examples and make runnable

### PR DESCRIPTION
**Pull request by prasannavl**
## Description

Make examples runnable with:
`cargo run -p examples --bin <example_name>` (or) 
`cargo run --bin <example_name>` (from examples dir)

Resolves https://github.com/rustasync/tide/issues/223

(Wait until to avoid conflicts: https://github.com/rustasync/tide/pull/220)

## Motivation and Context

https://github.com/rustasync/tide/pull/219#pullrequestreview-236996850
https://github.com/rustasync/tide/pull/219#discussion_r283687631

## How Has This Been Tested?

All examples functional

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactor

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/rustasync/tide/blob/master/.github/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Related issue https://github.com/rustasync/tide/issues/225 -- our new examples structure broke our dependency automation. We should probably find a way to fix that.

**Comment by prasannavl** [comment]
Waiting this one out until #220 - then choose from one of #225.

**Comment by prasannavl** [comment]
Rebased and merge-able. However still doesn't resolve #225. Is it an option to wait a few days to see https://github.com/dependabot/dependabot-core/issues/1156 is fixed, and if not rename it to `example`?

**Comment by yoshuawuyts** [comment]
It looks like this requires another rebase also.

**Comment by yoshuawuyts** [comment]
Commented in https://github.com/rustasync/tide/issues/223#issuecomment-494184444.

**Comment by prasannavl** [comment]
Closing, as #247 resolves this nicely.

**Pull request closed without merging**
